name = "Planets"
uuid = "d2fb0640-a787-40f6-ad8d-83a8a732c801"
authors = ["David James <davidabraham@ucla.edu>"]
version = "0.1.0"

[deps]
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
